config/routes.rb
Rails.application.routes.draw do

  resources :password_resets

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins, controller: 'users', type: 'Admin'
  resources :instructors, controller: 'users', type: 'Instructor'
  resources :teaching_assistants, controller: 'users', type: 'TeachingAssistant'
  
  resources :students, controller: 'users', type: 'Student' do
    resources :enrollments
    resources :submissions, only: [:index, :show, :edit, :update, :destroy]
  end

  resources :locations
  resources :courses
  resources :cohorts
  resources :comments
  resources :users do
    resources :notifications
  end
  resources :assignments do
    resources :submissions, only: [:new, :create, :index]
  end
  resources :submissions

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "reset_password" => "sessions#reset_password"
  post "reset_password/sending" => "sessions#send_reset_code"
  post "notification/review" => "notifications#mark_reviewed"

  root 'users#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :cohort
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :submissions
  has_many :notifications, as: :notifieable, dependent: :destroy

  #after_create :notify_cohort

  def get_student_submission(student)
    self.submissions.where(student_id: student.id)
  end

  def notify_cohort
    NewAssignmentJob.new.async.perform(self.cohort.users, self)
  end

  # state_machine initial: :new do
  #   state :reviewing
  #   state :complete
  #   state :incomplete

  #   event :review do
  #     transition :new => :reviewing
  #   end

  #   event :accept do
  #     transition :reviewing => :complete
  #   end

  #   event :reject do
  #     transition :reviewing => :incomplete
  #   end

  # end


end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_filter :is_instructor, only: [:new, :create, :edit, :update, :destroy]

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to instructors_path, notice: "Assignment added!"
    else
      render :new, alert: "Oops, there was an error."
    end
  end

  def index
  end

  def show
    Notification.mark_reviewed(params[:id], current_user.id)
    @new_comment = @assignment.comments.build
  end

  def edit
  end

  def update
    if @assignment.update_attributes(assignment_params)
      redirect_to @assignment, notice: "Assignment updated!"
    else
      render :edit, alert: "Oops, there was an error."
    end
  end

  def destroy
    if @assignment.destroy
      redirect_to instructors_path, notice: "Assignment deleted!"
    else
      redirect_to instructors_path, notice: "Oops, there was an error in deleting the assignment."
    end
  end

  private

  def assignment_params
    params.require(:assignment).permit(:title, :due_date, :content, :cohort_id)
  end

  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  def is_instructor
    if !current_user.is_instructor? then choose_path(current_user) end
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper

end

app/views/assignments/_assignment.html.haml
%a.btn.btn-lg.btn-info{href: assignment_path(assignment), style: "width: 33%;"}
  %strong= assignment.title
  %h5= assignment.due_date

app/views/assignments/_form.html.haml
= f.hidden_field :cohort_id, value: current_user.cohort.id
= f.label :title
= f.text_field :title
%br
= f.label :content
= f.text_area :content
%br
= f.label "Due on: "
= f.date_select :due_date
%br
= f.submit "Save Assignment", class: "btn btn-md btn-success"
= link_to "Cancel", instructors_path, class: "btn btn-md btn-default"

app/views/assignments/_instructor_options.html.haml
= link_to "Delete Assignment", assignment_path(assignment), method: "delete", class: "btn btn-xs btn-danger", :data => {confirm: "This is permanent. Are you sure you'd like to remove the assignment, it's comments, and submissions?"}

%br
%br

- if assignment.submissions
  %h3 Student Submissions
  %table.table.table-striped.table-hover
    %thead
      %th Student
      %th Submitted at
      %th
      %th
      %th
    %tbody
      - assignment.submissions.each do |submission|
        %tr
          %td= submission.student.full_name
          %td= submission.created_at
          %td
          %td
          %td

app/views/assignments/_student_options.html.haml
- if my_submission(assignment).nil?
  = link_to "Complete Assignment", new_assignment_submission_path(assignment), class: "btn btn-sm btn-primary"
- else
  %p= link_to "View My Submission", student_submission_path(current_user, my_submission(assignment))
  %p= link_to "Edit My Submission", edit_submission_path(my_submission(assignment))
  %p= my_submission(assignment).content

app/views/assignments/_ta_options.html.haml
%br
%br

- if assignment.submissions
  %h3 Student Submissions
  %table.table.table-striped.table-hover
    %thead
      %th Student
      %th Submitted at
      %th
      %th
      %th
    %tbody
      - assignment.submissions.each do |submission|
        %tr
          %td= link_to "#{submission.student.full_name}", submission
          %td= submission.created_at
          %td
          %td
          %td

app/views/assignments/edit.html.haml
%h1 Edit Assignment
%br
= form_for @assignment do |f|
  = render 'form', f:f

app/views/assignments/new.html.haml
%h1 New Assignment
%br
= form_for Assignment.new do |f|
  = render 'form', f:f

app/views/assignments/show.html.haml
= link_to "Back to All Assignments", cohort_path(@assignment.cohort), class: "btn btn-sm btn-default"
%br
%br
%legend
  = @assignment.title
  - if current_user.type == "Instructor"
    = link_to "Edit Assignment", edit_assignment_path(@assignment), class: "btn btn-xs btn-primary"
  %br
%p= @assignment.content
%strong= @assignment.due_date
%br
%br


%br
- case current_user.type
  - when "Instructor"
    = render 'instructor_options', assignment: @assignment
  - when "TeachingAssistant"
    = render 'ta_options', assignment: @assignment
  - when "Student"
    = render 'student_options', assignment: @assignment

%br
%br
%br
.row
  .col-md-2
  .col-md-8
    Comments
    %table.table
      - @assignment.comments.each do |comment|
        - if comment.created_at.nil?
          %tr
            %td
              %p= comment.content
        - else
          %tr
            %td
              %p= comment.content
              %p= time_since(comment)
    = form_for @new_comment, url: comments_path, method: :post do |f|
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :commentable_id, value: @assignment.id
      = f.hidden_field :commentable_type, value: "Assignment"
      .col-md-4
        = f.text_area :content, :class => "form-control"
      = f.submit "Leave Comment", :class => "btn btn-info"
  .col-md-2