config/routes.rb
Rails.application.routes.draw do

  resources :password_resets

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins, controller: 'users', type: 'Admin'
  resources :instructors, controller: 'users', type: 'Instructor'
  resources :teaching_assistants, controller: 'users', type: 'TeachingAssistant'
  
  resources :students, controller: 'users', type: 'Student' do
    resources :enrollments
    resources :submissions, only: [:index, :show, :edit, :update, :destroy]
  end

  resources :locations
  resources :courses
  resources :cohorts
  resources :comments
  resources :users do
    resources :notifications
  end
  resources :assignments do
    resources :submissions, only: [:new, :create, :index]
  end
  resources :submissions

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "reset_password" => "sessions#reset_password"
  post "reset_password/sending" => "sessions#send_reset_code"
  post "notification/review" => "notifications#mark_reviewed"

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :type

  has_many :comments
  has_many :notifications, dependent: :destroy

  after_create :welcome_user

  scope :admins, -> { where(type: 'Admin') }
  scope :instructors, -> { where(type: 'Instructor') }
  scope :teaching_assistants, -> { where(type: 'TeachingAssistant') }
  scope :students, -> { where(type: 'Student') }

  def welcome_user
    WelcomeUserJob.new.async.perform(self)
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    PasswordResetJob.new.async.perform(self)
  end

  def full_name
    first_name.capitalize + " " + last_name.capitalize
  end

  def is_admin?
    type == "Admin"
  end

  def is_instructor?
    type == "Instructor"
  end

  private

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64(8)
    end while User.exists?(column => self[column])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_filter :ensure_logged_in, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_type

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "Account created!"
    else
      render :new, notice: "Sorry, registration failed."
    end
  end

  def index
    @users = get_users(current_user)
    @type = current_user.type
  end

  def show
  end

  def edit
    @user = current_user.is_admin? ? User.find(params[:id]) : current_user
  end
  
  def update
    if @user.update_attributes(user_params)
      choose_path(@user)
    else
      render :edit, notice: "Sorry, there was an error. Please try again later."
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy! unless @user.id == current_user.id
    choose_path(@user)
  end

  private

  def user_params
    params.require(type.underscore.to_sym).permit(:first_name, :last_name, :type, :email, :password, :password_confirmation)
  end

  def set_user
    if User.where(id: params[:id]).exists?
      @user = type_class.find(params[:id])
    else
      @user = current_user
    end
  end

  def set_type 
    @type = type 
  end

  def type 
    params[:type] || "User" 
  end

  def type_class 
    type.constantize 
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_types
    user_types = ["Admin", "Instructor", "TeachingAssistant", "Student"]
  end

  def sti_user_path(type = "user", user = nil, action = nil)
    send "#{format_sti(action, type, user)}_path", user
  end

  def format_sti(action, type, user)
    action || user ? "#{format_action(action)}#{type.underscore}" : "#{type.underscore.pluralize}"
  end

  def format_action(action)
    action ? "#{action}_" : ""
  end

  def my_submission(assignment_id)
    @my_submission = current_user.get_my_submission(assignment_id).first
  end

end

app/views/users/_admin_panel.html.haml
%table.table.table-striped.table-hover
  %thead
    %th Name
    %th Email
    %th Role
    %th
    %th
    %th
  %tbody
    - @users.each do |user|
      = render 'user', user: user
%br
%br
.row
  .col-md-4
    %h3
      Locations
      = link_to "New Location", new_location_path, class: "btn btn-xs btn-success"
    %legend
    - unless Location.all.count == 0
      %ul
        - Location.all.each do |location|
          %li
            = link_to "#{location.where}", edit_location_path(location), class: "btn btn-xs btn-list"
            = link_to "X", location_path(location), method: "delete", class: "btn btn-xs btn-danger list-item", :data => {confirm: "Delete #{location.where}? This is permanent."}
          %br
  .col-md-4
    %h3
      Courses
      = link_to "New Course", new_course_path, class: "btn btn-xs btn-success"
    %legend
    - unless Course.all.count == 0
      %ul
        - Course.all.each do |course|
          %li
            = link_to "#{course.title}", edit_course_path(course), class: "btn btn-xs btn-list"
            = link_to "X", course_path(course), method: "delete", class: "btn btn-xs btn-danger list-item", :data => {confirm: "Delete #{course.title}? This is permanent."}
          %br
    %br
  .col-md-4
    %h3
      Cohorts
      = link_to "New Cohort", new_cohort_path, class: "btn btn-xs btn-success"
    %legend
    - unless Cohort.all.count == 0
      %ul#cohorts
        - Cohort.all.each do |cohort|
          %li
            = link_to "#{cohort.listing}", edit_cohort_path(cohort), class: "btn btn-xs btn-list"
            = link_to "X", cohort_path(cohort), method: "delete", class: "btn btn-xs btn-danger list-item", :data => {confirm: "Delete this #{cohort.listing}? This is permanent."}
            %div.hidden-date= cohort.start_date
          %br

app/views/users/_form.html.haml
First Name:
= f.text_field :first_name
%br
Last Name:
= f.text_field :last_name
%br
Role is:
- if current_user && current_user.type != "Admin"
  = f.label "#{current_user.type}"
- else
  = f.select :type, user_types.each.collect {|c| [c, c]}
%br
Email:
= f.email_field :email
%br
Password
= f.password_field :password
%br
Password Confirmation
= f.password_field :password_confirmation
%br
= f.submit "Submit"

app/views/users/_instructor_panel.html.haml
- if current_user.cohort
  %h3= "My Students for #{current_user.cohort.listing}"
  %table.table.table-striped.table-hover
    %thead
      %th Name
      %th Email
      %th
      %th
      %th
    %tbody
      - @users.each do |user|
        = render 'student', student: user
  %br
  %br
  %h3
    = "Our Assignments for #{current_user.cohort.listing}"
    = link_to "Add an Assignment", new_assignment_path, class: "btn btn-xs btn-success"

  %legend
  .row
    = render current_user.cohort.assignments unless nil
- else
  %h3 You aren't teaching any courses at the moment.
%br
%br
.row
  .col-md-4
    %h3 Where You Can Find Us
    %legend
    - unless Location.all.count == 0
      %ul
        - Location.all.each do |location|
          %li
            %div.btn.btn-xs.btn-list
              = location.where
          %br
  .col-md-4
    %h3 Courses We Provide
    %legend
    - unless Course.all.count == 0
      %ul
        - Course.all.each do |course|
          %li
            %div.btn.btn-xs.btn-list
              = course.title
          %br
    %br
  .col-md-4
    %h3 Upcoming Cohorts
    %legend
    - unless Cohort.all.count == 0
      %ul
        - Cohort.all.each do |cohort|
          %li
            %div.btn.btn-xs.btn-list
              = cohort.listing
            %div.hidden-date= cohort.start_date
          %br

app/views/users/_student.html.haml
%tr
  %td= student.full_name
  %td= student.email
  %td
  %td
  %td

app/views/users/_student_panel.html.haml
%h1
  Active Enrollments

%table.table.table-striped.table-hover
  %thead
    %th What
    %th Where
    %th When
    %th
    %th
    %th
  %tbody
    - current_user.active_enrollments.each do |enrollment|
      = render enrollment
%br
%br
%h3
  My Enrollments
  = link_to "New Enrollment", new_student_enrollment_path(current_user.id), class: "btn btn-xs btn-success"

%table.table.table-striped.table-hover
  %thead
    %th What
    %th Where
    %th When
    %th
    %th
    %th
  %tbody
    = render current_user.enrollments unless nil

%br
%br
.row
  .col-md-4
    %h3 Where You Can Find Us
    %legend
    - unless Location.all.count == 0
      %ul
        - Location.all.each do |location|
          %li
            %div.btn.btn-xs.btn-list
              = location.where
          %br
  .col-md-4
    %h3 Courses We Provide
    %legend
    - unless Course.all.count == 0
      %ul
        - Course.all.each do |course|
          %li
            %div.btn.btn-xs.btn-list
              = course.title
          %br
    %br
  .col-md-4
    %h3 Upcoming Cohorts
    %legend
    - unless Cohort.all.count == 0
      %ul
        - Cohort.all.each do |cohort|
          %li
            %div.btn.btn-xs.btn-list
              = cohort.listing
            %div.hidden-date= cohort.start_date
          %br

app/views/users/_ta_panel.html.haml
%h3 Cohort Students
%table.table.table-striped.table-hover
  %thead
    %th Name
    %th Email
    %th
    %th
    %th
  %tbody
    - @users.each do |user|
      = render 'student', student: user
%br
%br

%legend Cohort Assignments
.row
  = render current_user.cohort.assignments unless nil
%br
%br
.row
  .col-md-4
    %h3 Where You Can Find Us
    %legend
    - unless Location.all.count == 0
      %ul
        - Location.all.each do |location|
          %li
            %div.btn.btn-xs.btn-list
              = location.where
          %br
  .col-md-4
    %h3 Courses We Provide
    %legend
    - unless Course.all.count == 0
      %ul
        - Course.all.each do |course|
          %li
            %div.btn.btn-xs.btn-list
              = course.title
          %br
    %br
  .col-md-4
    %h3 Upcoming Cohorts
    %legend
    - unless Cohort.all.count == 0
      %ul
        - Cohort.all.each do |cohort|
          %li
            %div.btn.btn-xs.btn-list
              = cohort.listing
            %div.hidden-date= cohort.start_date
          %br

app/views/users/_user.html.haml
%tr
  %td= user.full_name
  %td= user.email
  %td= user.type
  %td
  %td= link_to "Edit User", edit_user_path(user), class: "btn btn-xs btn-info"
  %td= link_to "Delete User", user_path(user), method: "delete", :data => { confirm: "This is permanent! Are you sure you'd like to delete this user?" }, class: "btn btn-xs btn-danger"

app/views/users/edit.html.haml
Edit Profile
%br
= form_for @user do |f|
  = render 'form', f:f

app/views/users/index.html.haml
- case @type
- when "Admin"
  = render 'admin_panel'
- when "Student"
  = render 'student_panel'
- when "Instructor"
  = render 'instructor_panel'
- when "TeachingAssistant"
  = render 'ta_panel'
- else
  %h1 I work!

app/views/users/new.html.haml
Sign up!
%br
= form_for :user, url: users_path, method: :post do |f|
  = render "form", f:f
%br
= link_to "Sign In", new_session_path