config/routes.rb
Rails.application.routes.draw do

  resources :password_resets

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins, controller: 'users', type: 'Admin'
  resources :instructors, controller: 'users', type: 'Instructor'
  resources :teaching_assistants, controller: 'users', type: 'TeachingAssistant'
  
  resources :students, controller: 'users', type: 'Student' do
    resources :enrollments
    resources :submissions, only: [:index, :show, :edit, :update, :destroy]
  end

  resources :locations
  resources :courses
  resources :cohorts
  resources :comments
  resources :users do
    resources :notifications
  end
  resources :assignments do
    resources :submissions, only: [:new, :create, :index]
  end
  resources :submissions

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "reset_password" => "sessions#reset_password"
  post "reset_password/sending" => "sessions#send_reset_code"
  post "notification/review" => "notifications#mark_reviewed"

  root 'users#index'

end

app/models/submission.rb
class Submission < ActiveRecord::Base

  include Workflow

  workflow do
    state :new do
      event :review, transitions_to: :reviewed
    end
    state :reviewed do
      event :accept, transitions_to: :complete
      event :reject, transitions_to: :incomplete
    end
    state :complete
    state :incomplete do
      event :review, transitions_to: :reviewed
    end
  end

  belongs_to :student
  belongs_to :assignment
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :notifications, as: :notifieable, dependent: :destroy

  after_create :new_submission_notification

  def new_submission_notification
    NewSubmissionJob.new.async.perform(self)
    # self.student.new_submission_notification(self)
  end
  
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :set_assignment, only: [:new, :create]

  def new
    @submission = @assignment.submissions.new
  end

  def create
    @submission = @assignment.submissions.new(submission_params)
    if @submission.save
      redirect_to @assignment
    else
      render :new, notice: "Oops, there was a problem creating your submission."
    end
  end

  def index
  end

  def show
    Notification.mark_reviewed(params[:id], current_user.id)
    @new_comment = @submission.comments.build
  end

  def edit
  end

  def update
    if @submission.update_attributes(submission_params)
      redirect_to assignment_path(@submission.assignment.id)
    else
      render :edit, notice: "Oops, there was a problem updating your submission."
    end
  end

  def destroy
    temp = @submission.assignment
    if @submission.destroy
      redirect_to assignment_path(temp)
    else
      render :show
    end
  end

  private

  def submission_params
    params.require(:submission).permit(:assignment_id, :content, :student_id)
  end

  def set_submission
    @submission = Submission.find(params[:id])
  end

  def set_assignment
    @assignment = Assignment.find(params[:assignment_id])
  end

end

app/views/submissions/_form.html.haml
= f.hidden_field :student_id, value: current_user.id
Your Submission:
%br
= f.text_area :content, style: "min-width:300px;height:100%;"
%br
= f.submit "Submit", class: "btn btn-md btn-success"

app/views/submissions/edit.html.haml
%h1 Update Submission
%br
= form_for @submission, method: "patch" do |f|
  = render 'form', f:f

app/views/submissions/new.html.haml
%h1 Your Submission
%br
= form_for @submission, url: assignment_submissions_path do |f|
  = render 'form', f:f

app/views/submissions/show.html.haml
= link_to "Back to Assignment", @submission.assignment, class: "btn btn-sm btn-default"
%br
%h1 Submission
%br
%p= "by #{@submission.student.full_name}"
%p= @submission.content
%br
%br
%br
.row
  .col-md-2
  .col-md-8
    Comments
    %table.table
      - @submission.comments.each do |comment|
        - if comment.created_at.nil?
          %tr
            %td
              %p= comment.content
        - else
          %tr
            %td
              %p= comment.content
              %p= time_since(comment)
    = form_for @new_comment, url: comments_path, method: :post do |f|
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :commentable_id, value: @submission.id
      = f.hidden_field :commentable_type, value: "Submission"
      .col-md-4
        = f.text_area :content, :class => "form-control"
      = f.submit "Leave Comment", :class => "btn btn-info"
  .col-md-2