config/routes.rb
Rails.application.routes.draw do

  resources :password_resets

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins, controller: 'users', type: 'Admin'
  resources :instructors, controller: 'users', type: 'Instructor'
  resources :teaching_assistants, controller: 'users', type: 'TeachingAssistant'
  
  resources :students, controller: 'users', type: 'Student' do
    resources :enrollments
    resources :submissions, only: [:index, :show, :edit, :update, :destroy]
  end

  resources :locations
  resources :courses
  resources :cohorts
  resources :comments
  resources :users do
    resources :notifications
  end
  resources :assignments do
    resources :submissions, only: [:new, :create, :index]
  end
  resources :submissions

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "reset_password" => "sessions#reset_password"
  post "reset_password/sending" => "sessions#send_reset_code"
  post "notification/review" => "notifications#mark_reviewed"

  root 'users#index'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student, dependent: :destroy
  belongs_to :cohort, dependent: :destroy
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController

  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :set_enrollments, only: :index
  before_action :set_user

  def new
    @enrollment = Enrollment.new
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)
    if @enrollment.save
      redirect_to students_path, notice: "Enrollment created! Welcome aboard, matey."
    else
      render :new, alert: "Oops there was a problem with that. Try again later, please."
    end
  end

  def index
  end

  def show
    @enrollment = Enrollment.find(params[:id])
  end

  def edit
  end

  def update
    if @enrollment.update_attributes(enrollment_params)
      redirect_to students_path, notice: "Enrollment updated!"
    else
      render :edit, alert: "Oops! There was a problem, try again later, please."
    end
  end

  def destroy
    if @enrollment.destroy
      redirect_to students_path, notice: "Enrollment deleted."
    else
      render students_path, alert: "Oops! There was a problem, try again later, please."
    end
  end


  private

  def enrollment_params
    params.require(:enrollment).permit(:cohort_id, :student_id)
  end

  def set_user
    @user = current_user
  end

  def set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

  def set_enrollments
    @enrollments = current_user.enrollments
  end

end

app/views/enrollments/_enrollment.html.haml
%tr
  %td= link_to "#{enrollment.cohort.course.title}", cohort_path(enrollment.cohort)
  %td= enrollment.cohort.location.where
  %td= enrollment.cohort.when
  %td
  %td
  %td= link_to "Cancel Enrollment", student_enrollment_path(current_user, enrollment), method: "delete", :data => { confirm: "This is permanent! Are you sure you'd like to cancel this enrollment?" }, class: "btn btn-xs btn-danger"

app/views/enrollments/_form.html.haml
What Cohort would you like to attend?
= f.hidden_field :student_id, value: current_user.id
%br
- Cohort.all.each do |cohort|
  = f.label "#{cohort.listing}"
  = f.label "#{cohort.when}"
  = f.radio_button :cohort_id, cohort.id
%br
%br
= f.submit "Save Enrollment", class: "btn btn-sm btn-success", :data => { confirm: "Enroll?" }
= link_to "Cancel", students_path, class: "btn btn-sm btn-default"

/ Cohort.all.collect {|c| [(c.listing + " " + c.when), c.id]}

app/views/enrollments/new.html.haml
%h1 New Enrollment
%br
= form_for Enrollment.new, url: student_enrollments_path(current_user.id), method: "post" do |f|
  = render 'form', f:f